#thor:
# position controllers ---------------------------------------
  r_shoulder_pitch_position_controller:
    type: position_controllers/JointPositionController
    joint: r_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_shoulder_pitch_position_controller:
    type: position_controllers/JointPositionController
    joint: l_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_shoulder_roll_position_controller:
    type: position_controllers/JointPositionController
    joint: r_shoulder_roll
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_shoulder_roll_position_controller:
    type: position_controllers/JointPositionController
    joint: l_shoulder_roll
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_shoulder_yaw_position_controller:
    type: position_controllers/JointPositionController
    joint: r_shoulder_yaw
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_shoulder_yaw_position_controller:
    type: position_controllers/JointPositionController
    joint: l_shoulder_yaw
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_elbow_position_controller:
    type: position_controllers/JointPositionController
    joint: r_elbow
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_elbow_position_controller:
    type: position_controllers/JointPositionController
    joint: l_elbow
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_wrist_yaw1_position_controller:
    type: position_controllers/JointPositionController
    joint: r_wrist_yaw1
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_wrist_yaw1_position_controller:
    type: position_controllers/JointPositionController
    joint: l_wrist_yaw1
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_wrist_roll_position_controller:
    type: position_controllers/JointPositionController
    joint: r_wrist_roll
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_wrist_roll_position_controller:
    type: position_controllers/JointPositionController
    joint: l_wrist_roll
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_wrist_yaw2_position_controller:
    type: position_controllers/JointPositionController
    joint: r_wrist_yaw2
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_wrist_yaw2_position_controller:
    type: position_controllers/JointPositionController
    joint: l_wrist_yaw2
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_hip_yaw_position_controller:
    type: position_controllers/JointPositionController
    joint: r_hip_yaw
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_hip_yaw_position_controller:
    type: position_controllers/JointPositionController
    joint: l_hip_yaw
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_hip_roll_position_controller:
    type: position_controllers/JointPositionController
    joint: r_hip_roll
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_hip_roll_position_controller:
    type: position_controllers/JointPositionController
    joint: l_hip_roll
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_hip_pitch_position_controller:
    type: position_controllers/JointPositionController
    joint: r_hip_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_hip_pitch_position_controller:
    type: position_controllers/JointPositionController
    joint: l_hip_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_knee_position_controller:
    type: position_controllers/JointPositionController
    joint: r_knee
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_knee_position_controller:
    type: position_controllers/JointPositionController
    joint: l_knee
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_ankle_pitch_position_controller:
    type: position_controllers/JointPositionController
    joint: r_ankle_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_ankle_pitch_position_controller:
    type: position_controllers/JointPositionController
    joint: l_ankle_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}
  
  r_ankle_roll_position_controller:
    type: position_controllers/JointPositionController
    joint: r_ankle_roll
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_ankle_roll_position_controller:
    type: position_controllers/JointPositionController
    joint: l_ankle_roll
    pid: {p: 10.0, i: 0.0, d: 0.0}

  waist_pan_position_controller:
    type: position_controllers/JointPositionController
    joint: waist_pan
    pid: {p: 10.0, i: 0.0, d: 0.0}

  waist_tilt_position_controller:
    type: position_controllers/JointPositionController
    joint: waist_tilt
    pid: {p: 10.0, i: 0.0, d: 0.0}

  head_pan_position_controller:
    type: position_controllers/JointPositionController
    joint: head_pan
    pid: {p: 10.0, i: 0.0, d: 0.0}

  head_tilt_position_controller:
    type: position_controllers/JointPositionController
    joint: head_tilt
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_hand_thumb_position_controller:
    type: position_controllers/JointPositionController
    joint: r_hand_thumb
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_hand_thumb_position_controller:
    type: position_controllers/JointPositionController
    joint: l_hand_thumb
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_hand_index_finger_position_controller:
    type: position_controllers/JointPositionController
    joint: r_hand_index_finger
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_hand_index_finger_position_controller:
    type: position_controllers/JointPositionController
    joint: l_hand_index_finger
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_hand_middle_finger_position_controller:
    type: position_controllers/JointPositionController
    joint: r_hand_middle_finger
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_hand_middle_finger_position_controller:
    type: position_controllers/JointPositionController
    joint: l_hand_middle_finger
    pid: {p: 10.0, i: 0.0, d: 0.0}

  waist_lidar_position_controller:
    type: position_controllers/JointPositionController
    joint: waist_lidar
    pid: {p: 10.0, i: 0.0, d: 0.0}
